from __future__ import print_function
import requests
import json
import sys

with open('../../data/json/players_stats.json') as json_data:
    players = json.load(json_data, encoding='utf-8')

    for i, player in enumerate(players):
        print(i, end="\r")
        try:
            if('Release Clause' in player.keys()):
                r = requests.post('http://localhost:8000/api/v1/players/', data={
                'name': player['name'],
                'photo_url': player['photo_url'],
                'positions':player['positions'].split(','),
                'age': player['age'],
                'birth_date': player['birth_date'],
                'height': player['height'],
                'weight': player['weight'],
                'overall_rating': player['Overall Rating'],
                'potential': player['Potential'],
                'value': player['Value'],
                'wage': player['Wage'],
                'preferred_foot': player['Preferred Foot'],
                'international_reputation': player['International Reputation'],
                'weak_foot': player['Weak Foot'],
                'skill_moves': player['Skill Moves'],
                'work_rate': player['Work Rate'],
                'body_type': player['Body Type'],
                'real_face': player['Real Face'],
                'release_clause': player['Release Clause'],
                'player_hashtags': player['player_hashtags'].split(','),
                'social.follow': player['Follow'],
                'social.like': player['Like'],
                'social.dislike': player['Dislike'],
                'skills.crossing': player['Crossing'],
                'skills.finishing': player['Finishing'],
                'skills.heading_accuracy': player['HeadingAccuracy'],
                'skills.short_passing': player['ShortPassing'],
                'skills.volleys': player['Volleys'],
                'skills.dribbling': player['Dribbling'],
                'skills.curve': player['Curve'],
                'skills.fk_accuracy': player['FKAccuracy'],
                'skills.long_passing': player['LongPassing'],
                'skills.ball_control': player['BallControl'],
                'skills.acceleration': player['Acceleration'],
                'skills.sprint_speed': player['SprintSpeed'],
                'skills.agility': player['Agility'],
                'skills.reactions': player['Reactions'],
                'skills.balance': player['Balance'],                                                                       
                'skills.shot_power': player['ShotPower'],                                                                       
                'skills.jumping': player['Jumping'],                                                                       
                'skills.stamina': player['Stamina'],                                                                       
                'skills.strength': player['Strength'],                                                                       
                'skills.long_shots': player['LongShots'],                                                                       
                'skills.aggression': player['Aggression'],                                                                       
                'skills.interceptions': player['Interceptions'],                                                                       
                'skills.positioning': player['Positioning'],                                                                       
                'skills.vision': player['Vision'],                                                                       
                'skills.penalties': player['Penalties'],                                                                       
                'skills.composure': player['Composure'],                                                                       
                'skills.marking': player['Marking'],                                                                       
                'skills.standing_tackle': player['StandingTackle'],                                                                       
                'skills.sliding_tackle': player['SlidingTackle'],                                                                       
                'skills.gk_diving': player['GKDiving'],                                                                       
                'skills.gk_handling': player['GKHandling'],                                                                       
                'skills.gk_kicking': player['GKKicking'],                                                                       
                'skills.gk_positioning': player['GKPositioning'],                                                                       
                'skills.gk_reflexes': player['GKReflexes'],                                                                       
                'skills.gk_reflexes': player['GKReflexes'],
                'player_traits': player['player_traits'].split(','),                                                                                   
                })
                if(r.status_code != 201):
                    print(r.json())
            else:
                r = requests.post('http://localhost:8000/api/v1/players/', data={
                'name': player['name'],
                'photo_url': player['photo_url'],
                'positions':player['positions'].split(','),
                'age': player['age'],
                'birth_date': player['birth_date'],
                'height': player['height'],
                'weight': player['weight'],
                'overall_rating': player['Overall Rating'],
                'potential': player['Potential'],
                'value': player['Value'],
                'wage': player['Wage'],
                'preferred_foot': player['Preferred Foot'],
                'international_reputation': player['International Reputation'],
                'weak_foot': player['Weak Foot'],
                'skill_moves': player['Skill Moves'],
                'work_rate': player['Work Rate'],
                'body_type': player['Body Type'],
                'real_face': player['Real Face'],
                'player_hashtags': player['player_hashtags'].split(','),
                'social.follow': player['Follow'],
                'social.like': player['Like'],
                'social.dislike': player['Dislike'],
                'skills.crossing': player['Crossing'],
                'skills.finishing': player['Finishing'],
                'skills.heading_accuracy': player['HeadingAccuracy'],
                'skills.short_passing': player['ShortPassing'],
                'skills.volleys': player['Volleys'],
                'skills.dribbling': player['Dribbling'],
                'skills.curve': player['Curve'],
                'skills.fk_accuracy': player['FKAccuracy'],
                'skills.long_passing': player['LongPassing'],
                'skills.ball_control': player['BallControl'],
                'skills.acceleration': player['Acceleration'],
                'skills.sprint_speed': player['SprintSpeed'],
                'skills.agility': player['Agility'],
                'skills.reactions': player['Reactions'],
                'skills.balance': player['Balance'],                                                                       
                'skills.shot_power': player['ShotPower'],                                                                       
                'skills.jumping': player['Jumping'],                                                                       
                'skills.stamina': player['Stamina'],                                                                       
                'skills.strength': player['Strength'],                                                                       
                'skills.long_shots': player['LongShots'],                                                                       
                'skills.aggression': player['Aggression'],                                                                       
                'skills.interceptions': player['Interceptions'],                                                                       
                'skills.positioning': player['Positioning'],                                                                       
                'skills.vision': player['Vision'],                                                                       
                'skills.penalties': player['Penalties'],                                                                       
                'skills.composure': player['Composure'],                                                                       
                'skills.marking': player['Marking'],                                                                       
                'skills.standing_tackle': player['StandingTackle'],                                                                       
                'skills.sliding_tackle': player['SlidingTackle'],                                                                       
                'skills.gk_diving': player['GKDiving'],                                                                       
                'skills.gk_handling': player['GKHandling'],                                                                       
                'skills.gk_kicking': player['GKKicking'],                                                                       
                'skills.gk_positioning': player['GKPositioning'],                                                                       
                'skills.gk_reflexes': player['GKReflexes'],                                                                       
                'skills.gk_reflexes': player['GKReflexes'],
                'player_traits': player['player_traits'].split(','),                                                                                   
                })
                if(r.status_code != 201):
                    print(r.json())
        except requests.exceptions.RequestException as e:
            print(e)
            sys.exit(1)
        