from mongoengine import Document, EmbeddedDocument, fields

class PlayerSocial(EmbeddedDocument):
    follow = fields.IntField(required=True)
    like = fields.IntField(required=True)
    dislike = fields.IntField(required=True)

class PlayerSkills(EmbeddedDocument):
    crossing = fields.IntField(required=True)
    finishing = fields.IntField(required=True)
    heading_accuracy = fields.IntField(required=True)
    short_passing = fields.IntField(required=True)
    volleys = fields.IntField(required=True)
    dribbling = fields.IntField(required=True)
    curve = fields.IntField(required=True)
    fk_accuracy = fields.IntField(required=True)
    long_passing = fields.IntField(required=True)
    ball_control = fields.IntField(required=True)
    acceleration = fields.IntField(required=True)
    sprint_speed = fields.IntField(required=True)
    agility = fields.IntField(required=True)
    reactions = fields.IntField(required=True)
    balance = fields.IntField(required=True)
    shot_power = fields.IntField(required=True)
    jumping = fields.IntField(required=True)
    stamina = fields.IntField(required=True)
    strength = fields.IntField(required=True)
    long_shots = fields.IntField(required=True)
    aggression = fields.IntField(required=True)
    interceptions = fields.IntField(required=True)
    positioning = fields.IntField(required=True)
    vision = fields.IntField(required=True)
    penalties = fields.IntField(required=True)
    composure = fields.IntField(required=True)
    marking = fields.IntField(required=True)
    standing_tackle = fields.IntField(required=True)
    sliding_tackle = fields.IntField(required=True)
    gk_diving = fields.IntField(required=True)    
    gk_handling = fields.IntField(required=True)
    gk_kicking = fields.IntField(required=True)
    gk_positioning = fields.IntField(required=True)
    gk_reflexes = fields.IntField(required=True)

class Player(Document):
    name = fields.StringField(required=True, null=False)
    photo_url = fields.StringField(required=True, null=True)
    positions = fields.ListField(fields.StringField(required=True))
    age = fields.StringField(required=True)
    birth_date = fields.StringField(required=True)
    height = fields.IntField(required=True)
    weight = fields.IntField(required=True)
    overall_rating = fields.IntField(required=True)
    potential = fields.IntField(required=True)
    value = fields.StringField(required=True)
    wage = fields.StringField(required=True)
    preferred_foot = fields.StringField(required=True)
    international_reputation = fields.IntField(required=True)
    weak_foot = fields.IntField(required=True)
    skill_moves = fields.IntField(required=True)
    work_rate = fields.StringField(required=True)
    body_type = fields.StringField(required=True)
    real_face = fields.StringField(required=True)
    release_clause = fields.StringField(required=True)
    player_hashtags = fields.ListField(fields.StringField(required=True))
    social = fields.ListField(fields.EmbeddedDocumentField(PlayerSocial))
    skills = fields.ListField(fields.EmbeddedDocumentField(PlayerSkills))
    player_traits = fields.ListField(fields.StringField())

